name: UpdateETC
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch: ~
concurrency:
  group: etc
  cancel-in-progress: true
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Ini Repo
        uses: actions/checkout@v4
      - name: Ini Repo
        uses: actions/checkout@v4
        with: { path: tmp, ref: main }
      - name: Ini Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: tmp/requirements.txt
      - name: Ini Python
        run: |
          pip install -r tmp/requirements.txt
      - name: Run
        working-directory: tmp
        run: |
          ./run -a
          cp -rf out/* ..
      - name: Out Repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit --amend -m run
          git push -f
