gen:
  # text prepended to file name
  id: ""
  # variables refered with '='
  var:
    NodeList:
      - DIRECT
      - Node0
      - Node1
      - Node2
      - Node3
      - CN
      - DE
      - GB
      - HK
      - JP
      - SG
      - TW
      - US
      - Node
      - N-JMS
# misc data
meta:
  # lag test http link
  test: http://1.1.1.1/
  # plain dns server
  dns:
    - "1.1.1.1"
    - "1.0.0.1"
    - "[2606:4700:4700::1111]"
    - "[2606:4700:4700::1001]"
  # dns over https
  doh: https://cloudflare-dns.com/dns-query
# node info
node:
  - type: static
    # group name
    name: DEFAULT
    # group children, use '=' to insert predefined var
    list:
      - REJECT
      - =NodeList
    # group icon for ios
    ico-sf: arrow.left.arrow.right.system
  - type: static
    name: SYSTEM
    list:
      - DEFAULT
      - =NodeList
    ico-sf: arrow.left.and.right.system
  - type: static
    name: STREAM
    list:
      - DEFAULT
      - =NodeList
    ico-sf: arrow.left.and.right.system
  - type: static
    name: SPECFI
    list:
      - DEFAULT
      - =NodeList
    ico-sf: arrow.left.and.right.system
  - type: static
    name: R-CN
    list:
      - DEFAULT
      - =NodeList
    ico-sf: arrow.left.and.right.system
  - type: static
    name: R-JP
    list:
      - DEFAULT
      - =NodeList
    ico-sf: arrow.left.and.right.system
  - type: static
    name: R-TW
    list:
      - DEFAULT
      - =NodeList
    ico-sf: arrow.left.and.right.system
  - type: static
    name: R-US
    list:
      - DEFAULT
      - =NodeList
    ico-sf: arrow.left.and.right.system
  - type: static
    name: Node0
    # group children filter, use '=' to refer var/pattern:region
    list: .*
    ico-sf: arrow.triangle.branch.system
  - type: static
    name: Node1
    list: .*
    ico-sf: arrow.triangle.branch.system
  - type: static
    name: Node2
    list: .*
    ico-sf: arrow.triangle.branch.system
  - type: static
    name: Node3
    list: .*
    ico-sf: arrow.triangle.branch.system
  - type: test
    name: CN
    list: =cn
    ico-sf: arrow.triangle.swap.system
  - type: test
    name: DE
    list: =de
    ico-sf: arrow.triangle.swap.system
  - type: test
    name: GB
    list: =gb
    ico-sf: arrow.triangle.swap.system
  - type: test
    name: HK
    list: =hk
    ico-sf: arrow.triangle.swap.system
  - type: test
    name: JP
    list: =jp
    ico-sf: arrow.triangle.swap.system
  - type: test
    name: SG
    list: =sg
    ico-sf: arrow.triangle.swap.system
  - type: test
    name: TW
    list: =tw
    ico-sf: arrow.triangle.swap.system
  - type: test
    name: US
    list: =us
    ico-sf: arrow.triangle.swap.system
  - type: test
    name: Node
    list: .*
    ico-sf: arrow.triangle.swap.system
  - type: test
    name: N-JMS
    list: ^JMS-\d+@\w+s\d{1,2}\.\w+\.\w+:\d+
    ico-sf: arrow.triangle.swap.system
# filter info
filter:
  - type: gen
    # type gen will look into filter/ and call script to generate
    name: direct
    dest: DIRECT
  - type: gen
    name: system
    dest: SYSTEM
  - type: gen
    name: global
    dest: DEFAULT
  - type: gen
    name: stream
    dest: STREAM
  - type: gen
    name: specfi
    dest: SPECFI
  - type: gen
    name: r-cn
    dest: R-CN
  - type: ipgeo
    name: cn
    dest: R-CN
  - type: gen
    name: r-jp
    dest: R-JP
  - type: ipgeo
    name: jp
    dest: R-JP
  - type: gen
    name: r-tw
    dest: R-TW
  - type: ipgeo
    name: tw
    dest: R-TW
  - type: gen
    name: r-us
    dest: R-US
  - type: main
    # type main is the default dest and only the latter is valid
    dest: DEFAULT
