# base profile
id: ""
# variables refered with '=name'
var: {}
# misc options
misc:
  # lag test
  test: http://1.1.1.1/
  t-dns: nic.com@1.1.1.1
  # dns over udp
  dns:
    # - 1.1.1.1
    # - 1.0.0.1
    - 223.5.5.5
    - 223.6.6.6
  # dns over https
  doh:
    # - https://1.1.1.1/dns-query
    # - https://1.0.0.1/dns-query
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
# routing info
route:
  - id: main
    node:
      type: static
      name: Default
      list: [-direct, -reject, =node]
    filter:
      - type: main
      - use: world
    icon:
      sort: 0
      emoji: 🏳️‍🌈
      sf: arrow.left.arrow.right.system
  - id: cn
    node:
      type: static
      name: R-CN
      list: [-main, -direct, =node]
    filter:
      - use: cn
    icon:
      sort: 3
      emoji: 🏳️‍🌈
      sf: arrow.forward.system
  - id: jp
    node:
      type: static
      name: R-JP
      list: [-main, -direct, =node]
    filter:
      - use: jp
    icon:
      sort: 3
      emoji: 🏳️‍🌈
      sf: arrow.forward.system
  - id: tw
    node:
      type: static
      name: R-TW
      list: [-main, -direct, =node]
    filter:
      - use: tw
    icon:
      sort: 3
      emoji: 🏳️‍🌈
      sf: arrow.forward.system
  - id: us
    node:
      type: static
      name: R-US
      list: [-main, -direct, =node]
    filter:
      - use: us
    icon:
      sort: 3
      emoji: 🏳️‍🌈
      sf: arrow.forward.system
node:
  # type, static manual set dest, test set based on lag test
  # list, include proxy, = ref pattern.region
  # - { name: Node, type: test, list: =xx }
  # - { name: Node0, type: static, list: =xx }
  # - { name: Node1, type: static, list: =xx }
  # - { name: Node2, type: static, list: =xx }
  # - { name: Node3, type: static, list: =xx }
  - { name: NodeA, type: test, list: "\\[A\\]" }
  - { name: NodeB, type: test, list: "\\[B\\]" }
  - { name: NodeC, type: test, list: "\\[C\\]" }
  - { name: NodeD, type: test, list: "\\[D\\]" }
  - { name: CN, type: test, list: =cn }
  - { name: DE, type: test, list: =de }
  - { name: FR, type: test, list: =fr }
  - { name: GB, type: test, list: =gb }
  - { name: HK, type: test, list: =hk }
  - { name: JP, type: test, list: =jp }
  - { name: KR, type: test, list: =kr }
  - { name: NL, type: test, list: =nl }
  - { name: SG, type: test, list: =sg }
  - { name: TW, type: test, list: =tw }
  - { name: US, type: test, list: =us }
