# base profile
id: ""
# variables refered with '=name'
var: {}
# misc options
misc:
  # lag test http link
  test: http://1.1.1.1/
  t-dns: one.one.one.one@1.1.1.1
  # dns over udp on port 53
  dns:
    - "1.1.1.1"
    - "1.0.0.1"
    - "[2606:4700:4700::1111]"
    - "[2606:4700:4700::1001]"
  # dns over https
  doh: https://cloudflare-dns.com/dns-query
# routing info
route:
  - id: direct
    # user selector
    node: { id: direct }
    # package filter
    filter:
      - use: direct
  - id: system
    node:
      type: static
      name: SYSTEM
      list: [-main, -direct, =node]
    filter:
      - use: system
    icon:
      emoji: 🚩
      sf: arrow.left.and.right.system
  - id: main
    node:
      type: static
      name: DEFAULT
      list: [-direct, -reject, =node]
    filter:
      - type: main
      - use: world
    icon:
      emoji: 🚩
      sf: arrow.left.arrow.right.system
  - id: rcn
    node:
      type: static
      name: R-CN
      list: [-main, -direct, =node]
    filter:
      - use: rcn
    icon:
      emoji: 🚩
      sf: arrow.forward.system
  - id: rjp
    node:
      type: static
      name: R-JP
      list: [-main, -direct, =node]
    filter:
      - use: rjp
    icon:
      emoji: 🚩
      sf: arrow.forward.system
  - id: rtw
    node:
      type: static
      name: R-TW
      list: [-main, -direct, =node]
    filter:
      - use: rtw
    icon:
      emoji: 🚩
      sf: arrow.forward.system
  - id: rus
    node:
      type: static
      name: R-US
      list: [-main, -direct, =node]
    filter:
      - use: rus
    icon:
      emoji: 🚩
      sf: arrow.forward.system
node:
  # type, static manual set dest, test set based on lag test
  # list, include proxy, = ref pattern.region
  - { name: Node0, type: static, list: .* }
  - { name: Node1, type: static, list: .* }
  - { name: Node2, type: static, list: .* }
  - { name: Node3, type: static, list: .* }
  - { name: CN, type: test, list: =cn }
  - { name: DE, type: test, list: =de }
  - { name: GB, type: test, list: =gb }
  - { name: HK, type: test, list: =hk }
  - { name: JP, type: test, list: =jp }
  - { name: KR, type: test, list: =kr }
  - { name: SG, type: test, list: =sg }
  - { name: TW, type: test, list: =tw }
  - { name: US, type: test, list: =us }
  - { name: Node, type: test, list: .* }
  - name: N-JMS
    type: test
    list: ^JMS-\d+@c\d+s\d\d?\.\w+\.[a-z]+:\d+$
