# base profile
id: ""
# variables refered with '=name'
var: {}
# misc options
misc:
  # lag test http link
  test: http://one.one.one.one/
  t-dns: one.one.one.one@1.1.1.1
  # dns over udp on port 53
  dns:
    - "1.1.1.1"
    - "1.0.0.1"
    - "[2606:4700:4700::1111]"
    - "[2606:4700:4700::1001]"
  # dns over https
  doh: https://cloudflare-dns.com/dns-query
# routing info
route:
  - id: specfi
    # user selector
    node: { id: direct }
    # package filter
    filter:
      - use: specfi
  - id: system
    node:
      type: static
      name: SYSTEM
      list: [-main, -direct, =node]
    filter:
      - use: system
    icon:
      emoji: 🏳️‍🌈
      sf: arrow.left.and.right.system
  - id: main
    node:
      type: static
      name: DEFAULT
      list: [-direct, -reject, =node]
    filter:
      - type: main
      - use: ww
    icon:
      emoji: 🏳️‍🌈
      sf: arrow.left.arrow.right.system
  - id: cn
    node:
      type: static
      name: R-CN
      list: [-main, -direct, =node]
    filter:
      - use: cn
    icon:
      emoji: 🏳️‍🌈
      sf: arrow.forward.system
  - id: jp
    node:
      type: static
      name: R-JP
      list: [-main, -direct, =node]
    filter:
      - use: jp
    icon:
      emoji: 🏳️‍🌈
      sf: arrow.forward.system
  - id: tw
    node:
      type: static
      name: R-TW
      list: [-main, -direct, =node]
    filter:
      - use: tw
    icon:
      emoji: 🏳️‍🌈
      sf: arrow.forward.system
  - id: us
    node:
      type: static
      name: R-US
      list: [-main, -direct, =node]
    filter:
      - use: us
    icon:
      emoji: 🏳️‍🌈
      sf: arrow.forward.system
node:
  # type, static manual set dest, test set based on lag test
  # list, include proxy, = ref pattern.region
  - { name: Node0, type: static, list: "." }
  - { name: Node1, type: static, list: "." }
  - { name: Node2, type: static, list: "." }
  - { name: Node3, type: static, list: "." }
  - { name: NodeX, type: test, list: "\\[X\\]$" }
  - { name: NodeS, type: test, list: "." }
  - { name: CN, type: test, list: =cn }
  - { name: DE, type: test, list: =de }
  - { name: FR, type: test, list: =fr }
  - { name: GB, type: test, list: =gb }
  - { name: HK, type: test, list: =hk }
  - { name: JP, type: test, list: =jp }
  - { name: KR, type: test, list: =kr }
  - { name: SG, type: test, list: =sg }
  - { name: TW, type: test, list: =tw }
  - { name: US, type: test, list: =us }
