name: UpdateETC
on:
  schedule: [cron: 0 0 * * *]
  workflow_dispatch: ~
concurrency:
  group: etc
  cancel-in-progress: true
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Init Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Init Repo
        uses: actions/checkout@v4
        with: { ref: main }
      - name: Init Repo
        uses: actions/checkout@v4
        with: { ref: etc, path: out }
      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: pipenv
      - name: Run
        run: |
          ./run -a
