name: Gen to Pages
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # gen
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: |
          sudo apt install -y zsh
          ./run -a
      # pages
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: "./out"
      - uses: actions/deploy-pages@v2
        id: deployment
