name: Gen to Pages
on:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: github-pages
  cancel-in-progress: true
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # gen
      - uses: actions/checkout@v3
      - run: sudo apt install -y zsh
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: src/env/pip
      - run: pip install -r src/env/pip
      - run: ./run -g
      # pages
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with: { path: ./out }
      - uses: actions/deploy-pages@v2
        id: deployment
