name: Github Pages
on:
  schedule:
    - cron: 0 0 * * 0
concurrency:
  group: github-pages
  cancel-in-progress: true
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # env
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version-file: src/run/.python-version
          cache: pip
          cache-dependency-path: src/run/requirements.txt
      # gen
      - run: ./run -a
      # pages
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with: { path: ./out }
      - uses: actions/deploy-pages@v2
        id: deployment
